### ISSUE TITLE
Cannot read property '$new' of undefined?  [Angular 1.3.6] 

### ISSUE THREAD

**Issue by AJeezy9** [MoonStorm/trNgGrid#147]
Hi, 

I am looking towards this module to serve a more streamlined replacement for ui-grid, however I can't seem to get off the ground floor.

Regardless of whether I use your basic example or the data already being used and accessed in my controller, I am receiving the above error.

DevTools traces it to the following line of code: 
`var gridScope = angular.element($gridElement).scope().$new()`

While I would not consider myself an Angular novice, I still am learning the ropes and the error appears to arise from the creation and assignment of a new scope to the trNgGrid element -- an assignment I have no experience with in directives.

Do you have any idea what the problem is?  Could it have anything to do with the current version of Angular (1.3.6) that I am running?

Here is the complete error output I am receiving:

 TypeError: Cannot read property '$new' of undefined
    at GridController.setupScope (http://localhost:9000/basics/vendor/plugins/trNgGrid.js:306:49)
    at post (http://localhost:9000/basics/vendor/plugins/trNgGrid.js:901:56)
    at http://localhost:9000/basics/vendor/angular-136/angular.js:8188:44
    at invokeLinkFn (http://localhost:9000/basics/vendor/angular-136/angular.js:8194:9)
    at nodeLinkFn (http://localhost:9000/basics/vendor/angular-136/angular.js:7706:11)
    at compositeLinkFn (http://localhost:9000/basics/vendor/angular-136/angular.js:7062:13)
    at compositeLinkFn (http://localhost:9000/basics/vendor/angular-136/angular.js:7065:13)
    at nodeLinkFn (http://localhost:9000/basics/vendor/angular-136/angular.js:7701:24)
    at compositeLinkFn (http://localhost:9000/basics/vendor/angular-136/angular.js:7062:13)
    at publicLinkFn (http://localhost:9000/basics/vendor/angular-136/angular.js:6941:30) <table tr-ng-grid="" items="myItems" class="tr-ng-grid table table-bordered table-hover">

Also, whether proper or not, a prior issue led me to try to set up the $controllerProvider to allow globals, but this also had no effect on the error.

**Comment by MoonStorm** [comment]
It appears the current release of trNgGrid still works with 1.3.6: 
http://jsfiddle.net/MoonStorm/x286c7sg/

What is your exact scenario? Could you replicate it in a simple example?

**Comment by MoonStorm** [comment]
Closed due to inactivity.
